-- 103_crm_core.sql
--
-- The CRM module: clients, the contacts attached to them, orders, and — the part everything
-- else is built on — a full status transition history per order.
--
-- WHY A SEPARATE DOMAIN AND NOT boards/tasks. The obvious cheap move is "an order is a task on
-- a pipeline board, a status is a column". It was rejected deliberately:
--
--   * Every report the module exists to produce (New -> Closed cycle time, time-in-status,
--     bottleneck detection, SLA breach) needs an *entered/exited timestamp per status*. Tasks
--     record only their current column. There is nowhere to put the history without inventing
--     a task_status_history table, at which point "task" means two different things.
--   * An order needs a disposition on every transition and a mandatory reason on a losing one.
--     Columns cannot express either.
--   * lib/task-status.ts already carries scar tissue from the last time two status models were
--     reconciled by string matching (see CLAUDE.md §2). Adding a third meaning to `columns`
--     would repeat exactly that mistake.
--
-- WHY THE HISTORY IS WRITTEN BY A TRIGGER AND NOT THE CLIENT. The mockup's own stated
-- principle is "do not merely store the current status" — but a history the application is
-- trusted to append is a history that is wrong the first time any code path forgets. The
-- trigger below makes crm_orders.status and crm_order_status_history physically incapable of
-- disagreeing: the status column cannot change without closing the open interval and opening
-- the next one, in the same transaction as the UPDATE that caused it.
--
-- Purely additive: six new tables, one new enum-ish lookup table, one app_modules row. No
-- existing table, policy, grant or row is touched, so nothing that works today can break.
-- Paired rollback: scripts/rollback/103_revert.sql

BEGIN;

-- ── Statuses ─────────────────────────────────────────────────────────────────────────
-- A table rather than a CHECK constraint, mirroring public.task_statuses: the Administrator
-- role in the use-case doc "manages configuration", and renaming a stage must not be a
-- migration. `key` is the stable identifier reports group by; `label` is what humans see, and
-- is free to change without rewriting history.
CREATE TABLE IF NOT EXISTS public.crm_statuses (
  key            TEXT PRIMARY KEY,
  label          TEXT NOT NULL,
  position       INTEGER NOT NULL DEFAULT 0,
  -- Drives the pipeline board's colour and the dashboard tiles.
  color          TEXT NOT NULL DEFAULT '#6b7280',
  -- A terminal status stops the SLA clock: an order sitting in Won/Closed/Cancel is not
  -- "ageing", and counting it as such is what makes an aging report untrustworthy.
  is_terminal    BOOLEAN NOT NULL DEFAULT FALSE,
  -- Won vs Cancel are both terminal; only one of them counts toward conversion.
  is_won         BOOLEAN NOT NULL DEFAULT FALSE,
  -- "Lost Deal / Cancellation Reason * REQUIRED" in the intake mockup.
  requires_reason BOOLEAN NOT NULL DEFAULT FALSE,
  -- Hours in this status before the order is flagged on the aging panel. NULL = no target.
  sla_hours      INTEGER,
  is_archived    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.crm_statuses (key, label, position, color, is_terminal, is_won, requires_reason, sla_hours) VALUES
  ('new',                'New',                1, '#3b82f6', FALSE, FALSE, FALSE, 24),
  ('in_progress',        'In Progress',        2, '#10b981', FALSE, FALSE, FALSE, 72),
  ('pending_operations', 'Pending Operations',  3, '#f59e0b', FALSE, FALSE, FALSE, 48),
  ('hold',               'Hold',               4, '#ef4444', FALSE, FALSE, FALSE, NULL),
  ('ready_for_estimate', 'Ready for Estimate', 5, '#8b5cf6', FALSE, FALSE, FALSE, 48),
  ('won',                'Won',                6, '#16a34a', TRUE,  TRUE,  FALSE, NULL),
  ('closed',             'Closed',             7, '#6b7280', TRUE,  FALSE, FALSE, NULL),
  ('cancel',             'Cancel',             8, '#dc2626', TRUE,  FALSE, TRUE,  NULL)
ON CONFLICT (key) DO NOTHING;

-- ── Clients ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_clients (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Human-facing "C-10482". Generated by claim_crm_client_ref() so two intakes racing cannot
  -- mint the same number; the same advisory-lock shape as project ids (migration 090).
  client_ref     TEXT UNIQUE,
  company_name   TEXT,
  client_type    TEXT NOT NULL DEFAULT 'individual',
  address        TEXT,
  city           TEXT,
  state          TEXT,
  postal_code    TEXT,
  lead_source    TEXT,
  status         TEXT NOT NULL DEFAULT 'new' REFERENCES public.crm_statuses(key),
  -- SET NULL, not CASCADE: deleting the person who owned an account must not delete the
  -- account. This is the same rule migration 100 had to retrofit onto boards and comments.
  sales_rep_id   UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  operations_rep_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  estimated_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  notes          TEXT,
  created_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT crm_clients_type_known
    CHECK (client_type IN ('individual', 'business', 'family_trust', 'partner')),
  CONSTRAINT crm_clients_value_not_negative CHECK (estimated_value >= 0)
);

CREATE INDEX IF NOT EXISTS idx_crm_clients_status   ON public.crm_clients (status, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_crm_clients_sales_rep ON public.crm_clients (sales_rep_id);
-- The client list's search box hits name/company/email/phone; this covers the two on this
-- table. pg_trgm is not assumed to be installed, so it is a plain prefix-friendly lower() index.
CREATE INDEX IF NOT EXISTS idx_crm_clients_company  ON public.crm_clients (lower(company_name));

-- ── Contacts ─────────────────────────────────────────────────────────────────────────
-- "A client record can contain multiple individual contacts. Use + Add Customer for trusts,
-- families, partnerships, or other opportunities with multiple decision-makers."
CREATE TABLE IF NOT EXISTS public.crm_contacts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id    UUID NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
  first_name   TEXT NOT NULL,
  last_name    TEXT NOT NULL,
  email        TEXT,
  mobile_phone TEXT,
  -- Exactly one primary per client is enforced by the partial unique index below.
  is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
  position     INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_contacts_client ON public.crm_contacts (client_id, position);
CREATE INDEX IF NOT EXISTS idx_crm_contacts_email  ON public.crm_contacts (lower(email));
-- CASCADE here is correct and deliberate, unlike on the client: a contact is a part of its
-- client record, not an independent thing that should outlive it.
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_contacts_one_primary
  ON public.crm_contacts (client_id) WHERE is_primary;

-- ── Orders ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_orders (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no       TEXT UNIQUE,
  client_id      UUID NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
  order_type     TEXT NOT NULL DEFAULT 'standard',
  status         TEXT NOT NULL DEFAULT 'new' REFERENCES public.crm_statuses(key),
  owner_id       UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  priority       TEXT NOT NULL DEFAULT 'normal',
  estimated_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  target_close_date DATE,
  opened_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Set by the trigger when the order first enters a terminal status, cleared if reopened.
  -- Stored rather than derived so "average days to close" is one scan, not a lateral join.
  closed_at      TIMESTAMPTZ,
  created_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- ⚠️ Write-only carriers, never storage. The UI sets these in the SAME UPDATE that changes
  -- status; the trigger copies them onto the history row it opens and then blanks them again,
  -- so they are always NULL at rest. This is what lets a disposition be recorded atomically
  -- with the transition it describes: the alternative (a second write afterwards) leaves a
  -- window where the history says an order moved and cannot say why, and needs the history
  -- table to be application-writable, which is exactly what this module refuses to allow.
  status_change_reason TEXT,
  status_change_note   TEXT,
  CONSTRAINT crm_orders_priority_known CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  CONSTRAINT crm_orders_value_not_negative CHECK (estimated_value >= 0)
);

CREATE INDEX IF NOT EXISTS idx_crm_orders_client ON public.crm_orders (client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_crm_orders_status ON public.crm_orders (status, opened_at);
CREATE INDEX IF NOT EXISTS idx_crm_orders_owner  ON public.crm_orders (owner_id, status);
-- The aging panel asks "open orders past their target close date", so both parts are indexed.
CREATE INDEX IF NOT EXISTS idx_crm_orders_open_target
  ON public.crm_orders (target_close_date) WHERE closed_at IS NULL;

-- ── Status history: the reporting spine ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_order_status_history (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id    UUID NOT NULL REFERENCES public.crm_orders(id) ON DELETE CASCADE,
  status      TEXT NOT NULL REFERENCES public.crm_statuses(key),
  entered_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- NULL means "this is the interval the order is in right now". Exactly one open row per
  -- order, enforced by idx_crm_status_history_one_open below.
  exited_at   TIMESTAMPTZ,
  changed_by  UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  -- The "Reason / Disposition" dropdown: work proceeding normally, waiting on customer, etc.
  reason      TEXT,
  note        TEXT,
  CONSTRAINT crm_history_interval_ordered CHECK (exited_at IS NULL OR exited_at >= entered_at)
);

CREATE INDEX IF NOT EXISTS idx_crm_status_history_order
  ON public.crm_order_status_history (order_id, entered_at);
-- Cycle-time reporting scans by status and window; this is the index that report rides.
CREATE INDEX IF NOT EXISTS idx_crm_status_history_status
  ON public.crm_order_status_history (status, entered_at, exited_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_status_history_one_open
  ON public.crm_order_status_history (order_id) WHERE exited_at IS NULL;

-- ── Notes and documents ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_notes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id  UUID NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
  order_id   UUID REFERENCES public.crm_orders(id) ON DELETE CASCADE,
  -- SET NULL for the same reason task_comments got it in migration 100: the note is a record
  -- of what happened on the account and must survive the author being deprovisioned.
  author_id  UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  body       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_crm_notes_client ON public.crm_notes (client_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.crm_documents (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id    UUID NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
  order_id     UUID REFERENCES public.crm_orders(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  file_name    TEXT NOT NULL,
  mime_type    TEXT,
  size_bytes   BIGINT,
  uploaded_by  UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_crm_documents_client ON public.crm_documents (client_id, created_at DESC);

-- ── Reference generators ─────────────────────────────────────────────────────────────
-- Advisory-locked so two concurrent intakes cannot mint the same reference. Same shape as
-- claim_project_id (migration 090), which is where this pattern is already proven here.
CREATE OR REPLACE FUNCTION public.claim_crm_client_ref()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_next INTEGER;
BEGIN
  IF NOT private.is_active_user() THEN
    RAISE EXCEPTION 'not authorised to create clients' USING ERRCODE = '42501';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext('crm_client_ref'));
  SELECT COALESCE(MAX(NULLIF(regexp_replace(client_ref, '\D', '', 'g'), '')::INTEGER), 10000) + 1
    INTO v_next FROM public.crm_clients WHERE client_ref ~ '^C-\d+$';
  RETURN 'C-' || v_next::TEXT;
END;
$$;
REVOKE ALL ON FUNCTION public.claim_crm_client_ref() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_crm_client_ref() TO authenticated;

CREATE OR REPLACE FUNCTION public.claim_crm_order_no()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_prefix TEXT;
  v_seq    INTEGER;
BEGIN
  IF NOT private.is_active_user() THEN
    RAISE EXCEPTION 'not authorised to create orders' USING ERRCODE = '42501';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext('crm_order_no'));
  -- ORD-YYMMDD-#### matches the mockup's ORD-260813-1187.
  v_prefix := 'ORD-' || to_char(NOW(), 'YYMMDD');
  SELECT COALESCE(MAX(split_part(order_no, '-', 3)::INTEGER), 1000) + 1
    INTO v_seq FROM public.crm_orders WHERE order_no LIKE v_prefix || '-%';
  RETURN v_prefix || '-' || v_seq::TEXT;
END;
$$;
REVOKE ALL ON FUNCTION public.claim_crm_order_no() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_crm_order_no() TO authenticated;

-- ── The transition trigger ───────────────────────────────────────────────────────────
-- This is what makes the history trustworthy. It runs on INSERT (open the first interval) and
-- on any UPDATE that changes status (close the open interval, open the next), so
-- crm_orders.status and the history cannot drift apart no matter which code path writes.
-- ⚠️ Three registrations, not one, because the timings genuinely differ:
--   BEFORE INSERT — may still edit NEW (stamp closed_at) but the row does not exist yet, so
--                   writing history here fails the order_id foreign key. The migration's own
--                   post-condition caught exactly that on the first run.
--   AFTER  INSERT — the row exists, so the opening interval can reference it.
--   BEFORE UPDATE — the row exists AND NEW is still editable, so one pass does both.
CREATE OR REPLACE FUNCTION private.crm_record_status_transition()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_terminal BOOLEAN;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF TG_WHEN = 'BEFORE' THEN
      -- An order can be created already closed (backfilled/imported work).
      SELECT is_terminal INTO v_terminal FROM public.crm_statuses WHERE key = NEW.status;
      IF COALESCE(v_terminal, FALSE) AND NEW.closed_at IS NULL THEN
        NEW.closed_at := NEW.opened_at;
      END IF;
      RETURN NEW;
    END IF;

    INSERT INTO public.crm_order_status_history (order_id, status, entered_at, changed_by, reason, note)
    VALUES (NEW.id, NEW.status, NEW.opened_at, COALESCE(NEW.created_by, auth.uid()),
            NEW.status_change_reason, NEW.status_change_note);
    -- AFTER trigger: NEW is not writable here, so the carriers are cleared by a direct UPDATE
    -- that deliberately does not touch status (and so cannot re-enter this trigger).
    UPDATE public.crm_orders
       SET status_change_reason = NULL, status_change_note = NULL
     WHERE id = NEW.id
       AND (status_change_reason IS NOT NULL OR status_change_note IS NOT NULL);
    RETURN NULL;
  END IF;

  IF NEW.status IS NOT DISTINCT FROM OLD.status THEN
    RETURN NEW;
  END IF;

  -- Close the interval the order is leaving. There is exactly one open row per order
  -- (idx_crm_status_history_one_open), so this cannot close the wrong one.
  UPDATE public.crm_order_status_history
     SET exited_at = NOW()
   WHERE order_id = NEW.id AND exited_at IS NULL;

  INSERT INTO public.crm_order_status_history (order_id, status, entered_at, changed_by, reason, note)
  VALUES (NEW.id, NEW.status, NOW(), auth.uid(), NEW.status_change_reason, NEW.status_change_note);

  -- BEFORE trigger, so blanking the carriers is just an assignment on the row being written.
  NEW.status_change_reason := NULL;
  NEW.status_change_note   := NULL;

  SELECT is_terminal INTO v_terminal FROM public.crm_statuses WHERE key = NEW.status;
  -- Reopening clears closed_at, so an order that comes back out of Won/Closed stops counting
  -- as closed instead of permanently skewing "average days to close".
  NEW.closed_at := CASE WHEN COALESCE(v_terminal, FALSE) THEN NOW() ELSE NULL END;
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS crm_orders_status_history     ON public.crm_orders;
DROP TRIGGER IF EXISTS crm_orders_status_history_ins ON public.crm_orders;
DROP TRIGGER IF EXISTS crm_orders_status_history_new ON public.crm_orders;
DROP TRIGGER IF EXISTS crm_orders_status_history_upd ON public.crm_orders;

CREATE TRIGGER crm_orders_status_history_new
  BEFORE INSERT ON public.crm_orders
  FOR EACH ROW EXECUTE FUNCTION private.crm_record_status_transition();

CREATE TRIGGER crm_orders_status_history_ins
  AFTER INSERT ON public.crm_orders
  FOR EACH ROW EXECUTE FUNCTION private.crm_record_status_transition();

CREATE TRIGGER crm_orders_status_history_upd
  BEFORE UPDATE OF status ON public.crm_orders
  FOR EACH ROW EXECUTE FUNCTION private.crm_record_status_transition();

-- A transition on an order is activity on its client; the client list sorts by it.
CREATE OR REPLACE FUNCTION private.crm_touch_client()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.crm_clients
     SET last_activity_at = NOW()
   WHERE id = COALESCE(NEW.client_id, OLD.client_id);
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS crm_orders_touch_client ON public.crm_orders;
CREATE TRIGGER crm_orders_touch_client
  AFTER INSERT OR UPDATE ON public.crm_orders
  FOR EACH ROW EXECUTE FUNCTION private.crm_touch_client();

DROP TRIGGER IF EXISTS crm_notes_touch_client ON public.crm_notes;
CREATE TRIGGER crm_notes_touch_client
  AFTER INSERT ON public.crm_notes
  FOR EACH ROW EXECUTE FUNCTION private.crm_touch_client();

-- ── Grants and RLS ───────────────────────────────────────────────────────────────────
-- Supabase default-grants ALL on every new public table. 095 narrowed the defaults for tables
-- created by `postgres` (which the migration runner is), but the REVOKE is kept and asserted
-- below rather than assumed — the same reasoning as 097.
DO $grants$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'crm_statuses','crm_clients','crm_contacts','crm_orders',
    'crm_order_status_history','crm_notes','crm_documents'
  ] LOOP
    EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM authenticated', t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END
$grants$;

GRANT SELECT ON public.crm_statuses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_clients   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_contacts  TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_orders    TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_notes     TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_documents TO authenticated;
-- History is SELECT-only for everyone. It is written exclusively by the SECURITY DEFINER
-- trigger, which is the whole point: an audit trail an application can rewrite is not one.
-- UPDATE is granted on exited_at alone so nothing can retroactively edit what happened.
GRANT SELECT ON public.crm_order_status_history TO authenticated;

-- Statuses: everyone reads, admins configure.
DROP POLICY IF EXISTS "crm statuses readable" ON public.crm_statuses;
CREATE POLICY "crm statuses readable" ON public.crm_statuses
  FOR SELECT TO authenticated USING (private.is_active_user());

DROP POLICY IF EXISTS "crm statuses managed by admins" ON public.crm_statuses;
CREATE POLICY "crm statuses managed by admins" ON public.crm_statuses
  FOR ALL TO authenticated
  USING (private.is_admin_user()) WITH CHECK (private.is_admin_user());
GRANT INSERT, UPDATE, DELETE ON public.crm_statuses TO authenticated;

-- Clients / contacts / orders / notes / documents: this is a single-organisation product and
-- the CRM is a shared book of business, so every active member reads and writes it. Deleting
-- is deliberately narrowed to admins: a client record carries its orders and their history by
-- CASCADE, so an accidental delete destroys the reporting spine, not just a row.
DO $policies$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['crm_clients','crm_contacts','crm_orders','crm_notes','crm_documents'] LOOP
    EXECUTE format($p$DROP POLICY IF EXISTS "crm %1$s readable" ON public.%1$I$p$, t);
    EXECUTE format($p$CREATE POLICY "crm %1$s readable" ON public.%1$I
                      FOR SELECT TO authenticated USING (private.is_active_user())$p$, t);

    EXECUTE format($p$DROP POLICY IF EXISTS "crm %1$s insertable" ON public.%1$I$p$, t);
    EXECUTE format($p$CREATE POLICY "crm %1$s insertable" ON public.%1$I
                      FOR INSERT TO authenticated WITH CHECK (private.is_active_user())$p$, t);

    EXECUTE format($p$DROP POLICY IF EXISTS "crm %1$s updatable" ON public.%1$I$p$, t);
    EXECUTE format($p$CREATE POLICY "crm %1$s updatable" ON public.%1$I
                      FOR UPDATE TO authenticated
                      USING (private.is_active_user()) WITH CHECK (private.is_active_user())$p$, t);

    EXECUTE format($p$DROP POLICY IF EXISTS "crm %1$s deletable" ON public.%1$I$p$, t);
    EXECUTE format($p$CREATE POLICY "crm %1$s deletable" ON public.%1$I
                      FOR DELETE TO authenticated USING (private.is_admin_user())$p$, t);
  END LOOP;
END
$policies$;

-- A note is the one thing its own author may retract without being an admin.
DROP POLICY IF EXISTS "crm notes deletable by author" ON public.crm_notes;
CREATE POLICY "crm notes deletable by author" ON public.crm_notes
  FOR DELETE TO authenticated
  USING (private.is_active_user() AND author_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "crm history readable" ON public.crm_order_status_history;
CREATE POLICY "crm history readable" ON public.crm_order_status_history
  FOR SELECT TO authenticated USING (private.is_active_user());

-- ── Module registration ──────────────────────────────────────────────────────────────
-- Defaults OFF, like appointments (080): a module nobody has switched on must not appear in
-- everyone's navigation the moment this migration lands.
INSERT INTO public.app_modules (module_key, enabled)
VALUES ('crm', FALSE)
ON CONFLICT (module_key) DO NOTHING;

COMMENT ON TABLE public.crm_order_status_history IS
  'Append-only status intervals per order. Written only by private.crm_record_status_transition; '
  'authenticated holds SELECT and nothing else. Exactly one open (exited_at IS NULL) row per order.';

-- ── Post-conditions ──────────────────────────────────────────────────────────────────
DO $post$
DECLARE
  v_count   INTEGER;
  v_order   UUID;
  v_client  UUID;
  v_open    INTEGER;
  v_hist    INTEGER;
BEGIN
  SELECT count(*) INTO v_count FROM public.crm_statuses;
  IF v_count <> 8 THEN
    RAISE EXCEPTION '103 post-condition: expected 8 seeded statuses, found %', v_count;
  END IF;

  FOR v_count IN
    SELECT 1 FROM unnest(ARRAY['crm_statuses','crm_clients','crm_contacts','crm_orders',
                               'crm_order_status_history','crm_notes','crm_documents']) AS t(name)
    WHERE NOT (SELECT relrowsecurity FROM pg_class WHERE oid = ('public.' || t.name)::regclass)
  LOOP
    RAISE EXCEPTION '103 post-condition: RLS must be enabled on every crm table';
  END LOOP;

  -- anon must hold nothing anywhere in the module (095's rule, re-asserted per 097).
  IF EXISTS (
    SELECT 1 FROM unnest(ARRAY['crm_statuses','crm_clients','crm_contacts','crm_orders',
                               'crm_order_status_history','crm_notes','crm_documents']) AS t(name)
    WHERE has_table_privilege('anon', 'public.' || t.name, 'SELECT')
  ) THEN
    RAISE EXCEPTION '103 post-condition: anon must hold nothing on the crm tables';
  END IF;

  -- The audit trail must not be application-writable.
  IF has_table_privilege('authenticated', 'public.crm_order_status_history', 'INSERT')
     OR has_table_privilege('authenticated', 'public.crm_order_status_history', 'UPDATE')
     OR has_table_privilege('authenticated', 'public.crm_order_status_history', 'DELETE') THEN
    RAISE EXCEPTION '103 post-condition: status history must be SELECT-only for authenticated';
  END IF;

  -- Prove the trigger actually maintains the history, rather than trusting that it compiles.
  INSERT INTO public.crm_clients (company_name, client_type)
  VALUES ('__103_selftest__', 'business') RETURNING id INTO v_client;
  INSERT INTO public.crm_orders (client_id, order_no, status)
  VALUES (v_client, '__103_selftest__', 'new') RETURNING id INTO v_order;

  SELECT count(*) INTO v_hist FROM public.crm_order_status_history WHERE order_id = v_order;
  IF v_hist <> 1 THEN
    RAISE EXCEPTION '103 post-condition: INSERT must open exactly one interval, found %', v_hist;
  END IF;

  UPDATE public.crm_orders SET status = 'in_progress' WHERE id = v_order;
  UPDATE public.crm_orders
     SET status = 'won', status_change_reason = 'Work proceeding normally', status_change_note = 'self test'
   WHERE id = v_order;

  IF NOT EXISTS (
    SELECT 1 FROM public.crm_order_status_history
     WHERE order_id = v_order AND status = 'won'
       AND reason = 'Work proceeding normally' AND note = 'self test'
  ) THEN
    RAISE EXCEPTION '103 post-condition: the disposition must land on the interval it describes';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.crm_orders
     WHERE id = v_order
       AND (status_change_reason IS NOT NULL OR status_change_note IS NOT NULL)
  ) THEN
    RAISE EXCEPTION '103 post-condition: the status_change carriers must be blank at rest';
  END IF;

  SELECT count(*) INTO v_hist FROM public.crm_order_status_history WHERE order_id = v_order;
  SELECT count(*) INTO v_open FROM public.crm_order_status_history
   WHERE order_id = v_order AND exited_at IS NULL;
  IF v_hist <> 3 THEN
    RAISE EXCEPTION '103 post-condition: expected 3 intervals after 2 transitions, found %', v_hist;
  END IF;
  IF v_open <> 1 THEN
    RAISE EXCEPTION '103 post-condition: expected exactly 1 open interval, found %', v_open;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.crm_orders WHERE id = v_order AND closed_at IS NOT NULL) THEN
    RAISE EXCEPTION '103 post-condition: reaching a terminal status must stamp closed_at';
  END IF;

  -- Reopening must clear closed_at, or every cycle-time average is permanently wrong.
  UPDATE public.crm_orders SET status = 'in_progress' WHERE id = v_order;
  IF EXISTS (SELECT 1 FROM public.crm_orders WHERE id = v_order AND closed_at IS NOT NULL) THEN
    RAISE EXCEPTION '103 post-condition: reopening must clear closed_at';
  END IF;

  DELETE FROM public.crm_clients WHERE id = v_client;
  SELECT count(*) INTO v_hist FROM public.crm_order_status_history WHERE order_id = v_order;
  IF v_hist <> 0 THEN
    RAISE EXCEPTION '103 post-condition: deleting a client must cascade its order history';
  END IF;

  RAISE NOTICE '103 OK — crm schema ready, status-history trigger verified end to end';
END
$post$;

COMMIT;
