import {
  Bell,
  CheckSquare,
  Calendar,
  CalendarClock,
  Clock,
  Contact,
  Crown,
  FileBarChart,
  Filter,
  Flag,
  Gauge,
  Hash,
  History,
  Home,
  Kanban,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  Megaphone,
  MessageSquare,
  Plus,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Star,
  Tag,
  Target,
  Users,
  type LucideIcon,
} from 'lucide-react'

// Maps nav-model icon keys (plain strings, so the model stays dependency-free) to
// concrete lucide components. A missing key falls back to a neutral list icon.
const ICONS: Record<string, LucideIcon> = {
  'inbox-check': ListChecks,
  kanban: Kanban,
  bell: Bell,
  calendar: Calendar,
  appointments: CalendarClock,
  'project-ids': Hash,
  crm: Contact,
  agile: Gauge,
  strategy: Target,
  megaphone: Megaphone,
  lock: Lock,
  message: MessageSquare,
  shield: Shield,
  crown: Crown,
  home: Home,
  overview: LayoutDashboard,
  reports: FileBarChart,
  statuses: SlidersHorizontal,
  history: History,
  // Command-palette-only keys (commands.ts), not used by any nav item.
  plus: Plus,
  check: CheckSquare,
  search: Search,
  clock: Clock,
  link: Link2,
  star: Star,
  // Board context actions (buildBoardContextCommands / buildWorkItemContextCommands).
  filter: Filter,
  flag: Flag,
  settings: Settings,
  tag: Tag,
  users: Users,
}

export function navIcon(key: string): LucideIcon {
  return ICONS[key] ?? ListChecks
}
